[package]
name = "reformation"
version = "0.2.1"
authors = ["hukumka <hukumka212@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.1.0"
lazy_static = "1.2.0"

reformation_derive = {path="reformation_derive", version="0.2.1"}