[package]
name = "reparse_proc_macro"
version = "0.1.0"
authors = ["hukumka <hukumka212@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version="0.15", features = ["derive"] }
quote = "0.6"
proc-macro2 = "0.4"
regex = "1.1"

