[package]
name = "reformation_derive"
version = "0.2.1"
authors = ["hukumka <hukumka212@gmail.com>"]
edition = "2018"

license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = {version="0.15", features = ["derive"] }
quote = "0.6"
proc-macro2 = "0.4"

